### ISSUE TITLE
Unable to compile expression with quoted property name in context

### ISSUE THREAD

**Issue by dreadjr** [medikoo/es6-template-strings#5]
`template("${string}", { string: "123", '-created_at': 1233213 })`

**Comment by medikoo** [comment]
Thanks for reporting! Fixed and published with v2.0.1

**Comment by dreadjr** [comment]
Thanks but is there no way to access those variables? this['-created_at'] by changing the context of created function? Or wrap parameters in opts object?

**Comment by medikoo** [comment]
@dreadjr those names are invalid variables names, so it just can't work.

Same way you can't use such names in natively supported template literals, e.g. following code will throw syntax error in ES6 engine:

```javascript
var -created-at = 'foo';
var x = `bar ${ -created-at }`;
```

If you want to have access to such things, you need to wrap them with some object, e.g. following will work:

```javascript
var foo = {  '-created_at': 1233213 };
var x = `bar ${ foo['-created-at'] }`;
```

**Comment by dreadjr** [comment]
Yeah i get that, i was just curious if it would be value to "nest" the whole context object (internally), so then the problem would be avoided all together.

**Comment by medikoo** [comment]
@dreadjr what you're asking would not be what we want for most cases. If on your side you prefer context to be nested, just do it yourself, it's as easy as: `template(str, { nestedContext: context })`
