### ISSUE TITLE
Support for import

### ISSUE THREAD

**Issue by solidflows** [medikoo/es6-template-strings#7]
Hi, are there any plans to support the ability to import this library into other projects?

**Comment by medikoo** [comment]
@solidflows I'm not sure exactly what you mean.

This library is provided as CJS module, and can be directly imported by any project that consumes CJS modules format.

I'm closing it, but let's continue discusion if you still have some questions

**Comment by solidflows** [comment]
CJS works, but are there plans to support ES6 modules?
My project works with webpack and I'm importing libraries using

`import MyLib from 'mylib'`

**Comment by medikoo** [comment]
This library is intended to work in any ES5 environment without transpiliation, therefore ESM it's no go.

Webpack also supports CJS, so you should have no issues using this library with Webpack bundler
