### ISSUE TITLE
Error if no variable exists to swap data

### ISSUE THREAD

**Issue by solidflows** [medikoo/es6-template-strings#8]
This throws an error if there's a variable that is not mapped:

`resolveToString(compile('${servletUrl}?id=${id}'), {
  servletUrl: 'http://google.com'
})`

This returns an error because `id` was not replaced. Is this expected behavior?

Ideally I would like for it to return the string with whatever variables were passed and leave the unmatched vars alone. So the above would look like:
http://google.com?id=${id}

**Comment by medikoo** [comment]
@solidflows yes, it technically reflects _native_ behavior. The template string will crash if you would refernce not defined variable.

Still, there's an undocumented option `partial`, which addresses use case you're after (partial resolution of template).

Try:

```javascript
resolveToString(
  compile('${servletUrl}?id=${id}'), { servletUrl: 'http://google.com' }),
  { partial: true }
)
```

I'm going to leave this open, until this option is documented in main README.md

**Comment by solidflows** [comment]
Ok thanks, that works.
