### ISSUE TITLE
Double slash (`\\`) resolves to single slash (`\`)

### ISSUE THREAD

**Issue by kamronbatman** [medikoo/es6-template-strings#9]
I am trying to use this library to interpret placeholders in a yml file that has a regex. Unfortunately it is changing `\\` to `\` which is making the yml invalid.

**Comment by medikoo** [comment]
@kamronbatman it's per ECMAScript specification, `` `\\` `` will resolve with single `\` character

**Comment by kamronbatman** [comment]
Yeah that makes sense. Thanks!
